### ISSUE TITLE
Failed to tls handshake with logstash:5043 tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by manishrajkarnikar** [denibertovic/logstash-forwarder-dockerfile#8]
Getting this error

```
Failed to tls handshake with logstash:5043 tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

Here is my docker-compose.yml

```
elasticsearch:
    image: denibertovic/elasticsearch
    volumes:
        - ./logs/elasticsearch:/opt/elasticsearch/logs
        - ./config-examples/elasticsearch:/opt/elasticsearch/config
        - ./data/elasticsearch:/opt/elasticsearch/data
    ports:
        - "9200:9200"
        - "9300:9300"
    restart: always

logstash:
    image: denibertovic/logstash
    links:
        - elasticsearch
    volumes:
        - ./config-examples/logstash:/opt/conf
        - ./certs:/opt/certs
        - ./logs/logstash:/opt/logs
    ports:
        - "514:514"
        - "5043:5043"
        - "9292:9292"
    restart: always

kibana:
    image: denibertovic/kibana
    links:
        - elasticsearch
    volumes:
        - ./logs/kibana:/logs
        - ./config-examples/kibana:/kibana/config
    ports:
        - "5601:5601"
    restart: always

logforwarder:
  image: denibertovic/logstash-forwarder
  volumes:
    - ./config-examples/logstash_forwarder:/opt/conf
    - ./certs:/opt/certs
    - ./logs/app:/tmp/test
  links:
  - logstash
```

did run the makefile and can see logstash-forwarder.crt  and logstash-forwarder.key  in certs folder
